### ISSUE TITLE
Endpoints for specific image versions

### ISSUE THREAD

**Issue by tetron** [ga4gh/tool-registry-schemas#5]
Currently the API defines an endpoint `/tools/{registry-id}` which returns a "versions" field, which is an array of ToolVersion objects.  These provide a `global-id` but the format is not defined.  Suggest that it would be more in line with REST and Linked Data principals if individual versions have well defined URL endpoints, e.g. `/tools/{registry-id}/version/{version-id}`.

**Comment by tetron** [comment]
Also, versioned REST path should provide the "descriptor" and "dockerfile" endpoints as well, e.g. `/tools/{registry-id}/version/{version-id}/descriptor` and `/tools/{registry-id}/version/{version-id}/dockerfile`

**Comment by tetron** [comment]
Actually, I suggest the non-versioned endpoints go away entirely, but possibly allow for "floating" versions like `/{registry-id}/version/latest/descriptor`

**Comment by tetron** [comment]
Another feature of this approach is that the CWL metadata describes the base URL, so linked data properties of each version "just works":

```
<https://www.dockstore.org/tools/dockstore-tool-bamstats/version/1.25-2/descriptor> dct:creator <http://orcid.org/0000-0002-7681-6415>
```

**Comment by tetron** [comment]
@portah the last point relates to today's meeting

**Comment by denis-yuen** [comment]
re: third comment back

The non-versioned endpoint like `/tools/{registry-id}` actually returns a Tool object with nested ToolVersion objects inside it. I think that will remain useful if someone simply wants to grab all versions of a tool. 

Otherwise, I agree that the targeted endpoints like descriptor and dockerfile should always be versioned.

**Comment by tetron** [comment]
I agree, continuing to have a "versions" field with all versions listed is very useful for certain API consumers.

**Comment by tetron** [comment]
A couple more thoughts.

The ToolVersion should have a field that includes the full git commit hash of the tag.

We might want to consider having "version" be the commit hash and

**Comment by tetron** [comment]
No edit button on mobile sure?  Github fail.

Consider pros/cons of having the version portion of the URL be a git hash and provide tags as aliases.

Also think about how to provide docker image hash.

**Comment by tetron** [comment]
Bumpy train fail, keep hitting the wrong buttons :-)

**Comment by pgrosu** [comment]
No worries, this is very exciting :smile:

**Comment by denis-yuen** [comment]
I like git and all, but the decision as to whether to store documents in git or csv, svn, as simple files on a server somewhere, sounds like it would be an implementation detail for the registry implementer. 

So for the version id, I think I'd be satisfied if there's a unique version id of some sort (which a git hash probabilistically satisfies), but I'm hesitant to explicitly constrain it to git.

**Comment by osallou** [comment]
Agreeing, should not force any git ref, it is implementation related and
may not be so easy to get automatically by registries.

**Comment by pgrosu** [comment]
The git hash would just be a field and can be left blank if there is no commit there.  Why would a registry - which is defined as being internet-connected - not be able to easily get it from those registries?

**Comment by tetron** [comment]
Yes, could be a generic provenance field, maybe just a URL, and is up to the implementation to determine what URL to put there.  If accessing thorough standard API, still want to know where a container image came from, might want to modify it & make pull request.

**Comment by pgrosu** [comment]
I'm not building a repository, but I totally agree with you that the github hash should be available in a field.  It can allow to make Github the repository.  Github is ubiquitous and will make a lot of other things easier to use that come with github.  The version will also be self-describing, and folks would basically get a lot of things for free, literally :)  Again this does not diminish implementers from having other ones, but this is just too obvious not us just utilize it.  I think you might have mentioned this on Friday that these hashes can just be stored in a file - sorry I was in a noisy room that day, and it was hard to hear everything.

**Comment by portah** [comment]
@tetron Yep, agree, when I said API-SPARQL bridge I though about something like that. You formalized :) and gave a great example... I think someone owe you a box of beer )

**Comment by pgrosu** [comment]
And let's not forget, R even uses Github as one of it's repositories through `devtools`:

https://github.com/hadley/devtools

Then client only needs to know one general github web-link for the repository - which can also have list of repositories - and then it can discover the packages by querying all the stored metadata information on Github as well:

https://github.com/search?q=cwl&type=Repositories

All the query syntax is available here - and one can always add on top of that:

https://help.github.com/articles/search-syntax/

Again Github would be one of many, but definitely a +1 vote to have it as a field.

~p

**Comment by denis-yuen** [comment]
I think the compromise here is to add an optional generic URL field to both the model for the tool descriptor and the tool dockerfile, which can link to a specific git URL, hash included. 

Additionally, as I noted before, the version id, could be a git hash if desired, it is just not constrained that way. I think that satisfies both use cases. Updating schema to match

**Comment by tetron** [comment]
@denis-yuen yes, that sounds like a good compromise.

**Comment by denis-yuen** [comment]
Probably out-of-date, the 1.0 release contains a version-id that can be customized (and could be a hash).
