### ISSUE TITLE
URL for Version

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/tool-registry-schemas#6]
Would be nice to have a version string e.g. "V1" in the URL for the API.  Also, maybe put all "tools" under /GA4GH/<version>/tools instead.

That way you could have:

/GA4GH/<version>/repositories
.../tools
.../execute
.../write

**Comment by denis-yuen** [comment]
The basepath of the specification does define that everything should be under ```/api/v1``` https://github.com/ga4gh/tool-registry-schemas/blob/develop/src/main/resources/swagger/ga4gh-tool-discovery.yaml#L9
